// Social Media Footer Icons
// Adds WhatsApp, Facebook, Instagram icons to the footer

const SOCIAL_CONTACTS = {
  whatsapp: {
      phone: '01156918888',
          url: function() { return `https://wa.me/${this.phone.replace(/\D/g, '')}`; },
              icon: '💬',
                  color: '#25D366',
                      name: 'WhatsApp'
                        },
                          facebook: {
                              url: '', // Will be set when user provides it
                                  icon: 'f',
                                      color: '#1877F2',
                                          name: 'Facebook'
                                            },
                                              instagram: {
                                                  url: '', // Will be set when user provides it
                                                      icon: '📷',
                                                          color: '#E4405F',
                                                              name: 'Instagram'
                                                                }
                                                                };

                                                                function addSocialFooter() {
                                                                  // Wait for footer to exist
                                                                    const checkFooter = setInterval(() => {
                                                                        const footer = document.querySelector('footer') || document.querySelector('[data-section="footer"]');

                                                                            if (footer) {
                                                                                  clearInterval(checkFooter);
                                                                                        initSocialFooter(footer);
                                                                                            }
                                                                                              }, 500);

                                                                                                // If no footer found, create one
                                                                                                  setTimeout(() => {
                                                                                                      if (!document.querySelector('footer') && !document.querySelector('[data-section="footer"]')) {
                                                                                                            createFooter();
                                                                                                                }
                                                                                                                  }, 3000);
                                                                                                                  }
                                                                                                                  
                                                                                                                  function createFooter() {
                                                                                                                    const footer = document.createElement('footer');
                                                                                                                      footer.id = 'social-footer';
                                                                                                                        footer.style.cssText = `
                                                                                                                            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                                                                                                                                padding: 30px 20px;
                                                                                                                                    text-align: center;
                                                                                                                                        margin-top: 50px;
                                                                                                                                            border-top: 2px solid rgba(255,255,255,0.1);
                                                                                                                                              `;
                                                                                                                                              
                                                                                                                                                document.body.appendChild(footer);
                                                                                                                                                  initSocialFooter(footer);
                                                                                                                                                  }
                                                                                                                                                  
                                                                                                                                                  function initSocialFooter(footer) {
                                                                                                                                                    // Remove existing social icons if any
                                                                                                                                                      const existingSocialContainer = footer.querySelector('.social-icons-container');
                                                                                                                                                        if (existingSocialContainer) {
                                                                                                                                                            existingSocialContainer.remove();
                                                                                                                                                              }
                                                                                                                                                              
                                                                                                                                                                const socialContainer = document.createElement('div');
                                                                                                                                                                  socialContainer.className = 'social-icons-container';
                                                                                                                                                                    socialContainer.style.cssText = `
                                                                                                                                                                        display: flex;
                                                                                                                                                                            justify-content: center;
                                                                                                                                                                                gap: 20px;
                                                                                                                                                                                    flex-wrap: wrap;
                                                                                                                                                                                        margin-bottom: 20px;
                                                                                                                                                                                          `;
                                                                                                                                                                                          
                                                                                                                                                                                            // WhatsApp Icon
                                                                                                                                                                                              if (SOCIAL_CONTACTS.whatsapp.phone) {
                                                                                                                                                                                                  const whatsappIcon = createSocialIcon(
                                                                                                                                                                                                        SOCIAL_CONTACTS.whatsapp.name,
                                                                                                                                                                                                              SOCIAL_CONTACTS.whatsapp.url(),
                                                                                                                                                                                                                    SOCIAL_CONTACTS.whatsapp.color,
                                                                                                                                                                                                                          'whatsapp'
                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                  socialContainer.appendChild(whatsappIcon);
                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                      // Facebook Icon
                                                                                                                                                                                                                                        if (SOCIAL_CONTACTS.facebook.url) {
                                                                                                                                                                                                                                            const facebookIcon = createSocialIcon(
                                                                                                                                                                                                                                                  SOCIAL_CONTACTS.facebook.name,
                                                                                                                                                                                                                                                        SOCIAL_CONTACTS.facebook.url,
                                                                                                                                                                                                                                                              SOCIAL_CONTACTS.facebook.color,
                                                                                                                                                                                                                                                                    'facebook'
                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                            socialContainer.appendChild(facebookIcon);
                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                // Instagram Icon
                                                                                                                                                                                                                                                                                  if (SOCIAL_CONTACTS.instagram.url) {
                                                                                                                                                                                                                                                                                      const instagramIcon = createSocialIcon(
                                                                                                                                                                                                                                                                                            SOCIAL_CONTACTS.instagram.name,
                                                                                                                                                                                                                                                                                                  SOCIAL_CONTACTS.instagram.url,
                                                                                                                                                                                                                                                                                                        SOCIAL_CONTACTS.instagram.color,
                                                                                                                                                                                                                                                                                                              'instagram'
                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                      socialContainer.appendChild(instagramIcon);
                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                          footer.insertBefore(socialContainer, footer.firstChild);
                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                          function createSocialIcon(name, url, color, platform) {
                                                                                                                                                                                                                                                                                                                            const iconContainer = document.createElement('a');
                                                                                                                                                                                                                                                                                                                              iconContainer.href = url;
                                                                                                                                                                                                                                                                                                                                iconContainer.target = '_blank';
                                                                                                                                                                                                                                                                                                                                  iconContainer.rel = 'noopener noreferrer';
                                                                                                                                                                                                                                                                                                                                    iconContainer.title = name;
                                                                                                                                                                                                                                                                                                                                      iconContainer.className = `social-icon social-icon-${platform}`;
                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                        let svgIcon = '';
                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                          if (platform === 'whatsapp') {
                                                                                                                                                                                                                                                                                                                                              svgIcon = `
                                                                                                                                                                                                                                                                                                                                                    <svg viewBox="0 0 24 24" width="24" height="24" fill="white">
                                                                                                                                                                                                                                                                                                                                                            <path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.272-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.67-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.076 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421-7.403h-.004a9.87 9.87 0 00-4.946 1.27l-.355.192-.368-.06c-1.286-.23-2.428-.856-3.284-1.860l-.214-.289-.309.179c-.71.52-1.226 1.22-1.479 2.03-.363 1.126-.276 2.442.542 3.631 1.02 1.54 2.953 2.866 5.015 3.408 1.08.296 2.302.264 3.344-.042l.313-.082.313.093c.952.304 1.894.23 2.726-.193.66-.34 1.277-.815 1.822-1.386l.261-.3.238.239c.656.656 1.022 1.563 1.083 2.523.031.464-.057.858-.238 1.15-.332.554-.98.9-1.794.9-.67 0-1.385-.213-2.029-.657-.463-.32-1.06-.84-1.543-1.45-.297-.386-.645-.825-1.036-1.31-.485-.607-1.036-1.03-1.68-1.245z"/>
                                                                                                                                                                                                                                                                                                                                                                  </svg>
                                                                                                                                                                                                                                                                                                                                                                      `;
                                                                                                                                                                                                                                                                                                                                                                        } else if (platform === 'facebook') {
                                                                                                                                                                                                                                                                                                                                                                            svgIcon = `
                                                                                                                                                                                                                                                                                                                                                                                  <svg viewBox="0 0 24 24" width="24" height="24" fill="white">
                                                                                                                                                                                                                                                                                                                                                                                          <path d="M24 12.073c0-6.627-5.373-12-12-12s-12 5.373-12 12c0 5.99 4.388 10.954 10.125 11.854v-8.385H7.078v-3.47h3.047V9.43c0-3.007 1.792-4.669 4.533-4.669 1.312 0 2.686.235 2.686.235v2.953H15.83c-1.491 0-1.956.925-1.956 1.874v2.25h3.328l-.532 3.47h-2.796v8.385C19.612 23.027 24 18.062 24 12.073z"/>
                                                                                                                                                                                                                                                                                                                                                                                                </svg>
                                                                                                                                                                                                                                                                                                                                                                                                    `;
                                                                                                                                                                                                                                                                                                                                                                                                      } else if (platform === 'instagram') {
                                                                                                                                                                                                                                                                                                                                                                                                          svgIcon = `
                                                                                                                                                                                                                                                                                                                                                                                                                <svg viewBox="0 0 24 24" width="24" height="24" fill="white">
                                                                                                                                                                                                                                                                                                                                                                                                                        <path d="M12 0C8.74 0 8.333.015 7.053.072 5.775.132 4.905.333 4.117.63c-.794.297-1.473.648-2.148 1.323-.676.675-1.026 1.354-1.323 2.148-.297.788-.5 1.658-.56 2.936C.015 8.333 0 8.74 0 12s.015 3.667.072 4.947c.06 1.277.263 2.148.56 2.936.297.791.646 1.47 1.323 2.145.675.676 1.354 1.026 2.148 1.323.788.297 1.659.5 2.936.56C8.333 23.985 8.74 24 12 24s3.667-.015 4.947-.072c1.280-.06 2.147-.263 2.936-.56.791-.297 1.469-.647 2.145-1.323.676-.675 1.026-1.354 1.323-2.148.297-.788.5-1.658.56-2.936.057-1.28.072-1.687.072-4.947s-.015-3.667-.072-4.947c-.06-1.277-.263-2.149-.56-2.936-.297-.791-.646-1.469-1.323-2.145-.675-.676-1.354-1.026-2.148-1.323-.788-.297-1.659-.499-2.936-.559C15.667.015 15.26 0 12 0zm0 2.16c3.203 0 3.585.009 4.849.070 1.171.054 1.805.244 2.227.408.562.217.96.477 1.382.896.419.42.679.819.896 1.381.164.422.354 1.057.408 2.227.061 1.264.07 1.646.07 4.849s-.009 3.585-.07 4.849c-.054 1.171-.244 1.805-.408 2.227-.217.562-.477.96-.896 1.382-.42.419-.819.679-1.381.896-.422.164-1.057.354-2.227.408-1.264.061-1.646.07-4.849.07s-3.585-.009-4.849-.07c-1.171-.054-1.805-.244-2.227-.408-.562-.217-.96-.477-1.382-.896-.419-.42-.679-.819-.896-1.381-.164-.422-.354-1.057-.408-2.227-.061-1.264-.07-1.646-.07-4.849s.009-3.585.07-4.849c.054-1.171.244-1.805.408-2.227.217-.562.477-.96.896-1.382.42-.419.819-.679 1.381-.896.422-.164 1.057-.354 2.227-.408 1.264-.061 1.646-.07 4.849-.07zM5.838 12a6.162 6.162 0 1112.324 0 6.162 6.162 0 01-12.324 0zM12 16a4 4 0 110-8 4 4 0 010 8zm4.965-10.322a1.44 1.44 0 112.881.001 1.44 1.44 0 01-2.881-.001z"/>
                                                                                                                                                                                                                                                                                                                                                                                                                              </svg>
                                                                                                                                                                                                                                                                                                                                                                                                                                  `;
                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                      iconContainer.style.cssText = `
                                                                                                                                                                                                                                                                                                                                                                                                                                          width: 50px;
                                                                                                                                                                                                                                                                                                                                                                                                                                              height: 50px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                  border-radius: 50%;
                                                                                                                                                                                                                                                                                                                                                                                                                                                      background-color: ${color};
                                                                                                                                                                                                                                                                                                                                                                                                                                                          display: flex;
                                                                                                                                                                                                                                                                                                                                                                                                                                                              align-items: center;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  justify-content: center;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      transition: all 0.3s ease;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          box-shadow: 0 4px 15px rgba(0,0,0,0.2);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              text-decoration: none;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                `;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  iconContainer.innerHTML = svgIcon;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Hover effect
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      iconContainer.addEventListener('mouseenter', function() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          this.style.transform = 'scale(1.15) translateY(-5px)';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              this.style.boxShadow = `0 8px 25px ${color}80`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  iconContainer.addEventListener('mouseleave', function() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      this.style.transform = 'scale(1) translateY(0)';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          this.style.boxShadow = '0 4px 15px rgba(0,0,0,0.2)';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return iconContainer;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              // Initialize when DOM is ready
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              if (document.readyState === 'loading') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                document.addEventListener('DOMContentLoaded', addSocialFooter);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  addSocialFooter();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  // Watch for dynamic footer creation
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const observer = new MutationObserver(() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (!document.querySelector('.social-icons-container')) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const footer = document.querySelector('footer') || document.querySelector('[data-section="footer"]');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (footer) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  initSocialFooter(footer);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        observer.disconnect();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              observer.observe(document.body, { childList: true, subtree: true });
